ITEM.name = "Blood bag"
ITEM.model = "models/zworld_health/healthkit.mdl"
ITEM.description = "A simple blood bag with blood"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 0
ITEM.category = "Medicals"
ITEM.injuryCategory = {7} // Check sh_plugin.lua, line №6 PLUGIN.DEFAULT_LIMBS
ITEM.healAmount = 100; // The points that will be added when someone uses this
ITEM.useSound = "npc/barnacle/barnacle_digesting1.wav" // the sound when it used